#!/usr/bin/env python3
"""Generate deterministic SVG plots of representative local panel responses."""

from __future__ import annotations

import argparse
import hashlib
import math
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Final

import matplotlib

matplotlib.use("Agg")
matplotlib.rcParams.update(
    {
        "font.family": "DejaVu Sans",
        "font.size": 10.0,
        "path.simplify": False,
        "savefig.dpi": 100,
        "svg.fonttype": "path",
        "svg.hashsalt": "panel-solvers-doc-angle-response-v1",
    }
)

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.axes import Axes
from matplotlib.figure import Figure
from numpy.typing import NDArray

from panelsolver.core import ModelCasePayload, PanelFlowState, PanelGeometry
from panelsolver.models import HypersonicModel, SentmanModel
from panelsolver.models.hypersonic import (
    _tangent_cone_detach_limit,
    _tangent_wedge_detach_limit,
    modified_newtonian_cp_max,
)

FloatArray = NDArray[np.float64]

REPOSITORY_ROOT: Final = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR: Final = REPOSITORY_ROOT / "docs" / "assets" / "plots"
OUTPUT_FILENAMES: Final = (
    "sentman-local-traction-vs-angle.svg",
    "hypersonic-windward-cp-vs-angle.svg",
    "hypersonic-leeward-cp-vs-angle.svg",
)
GENERATOR_MARKER: Final = "scripts/generate_docs_angle_response_plots.py"

FLOW_DIRECTION_STL: Final = np.array([1.0, 0.0, 0.0], dtype=np.float64)
ANGLE_STEP_DEG: Final = 0.25
SENTMAN_SPEED_RATIO: Final = 7.0
SENTMAN_TI_K: Final = 1000.0
SENTMAN_WALL_TO_INCIDENT_SQRT: Final = 0.425
SENTMAN_TW_K: Final = SENTMAN_TI_K * SENTMAN_WALL_TO_INCIDENT_SQRT**2
HYPERSONIC_MACH: Final = 6.0
HYPERSONIC_GAMMA: Final = 1.4

FIGURE_SIZE_IN: Final = (8.0, 5.25)
FIGURE_DPI: Final = 100
PLOT_DECIMALS: Final = 6
SVG_METADATA: Final = {
    "Creator": "Panel Solver",
    "Date": None,
    "Description": f"Generated by {GENERATOR_MARKER}",
}

COLORS: Final = {
    "blue": "#0072B2",
    "orange": "#E69F00",
    "green": "#009E73",
    "red": "#D55E00",
    "purple": "#CC79A7",
    "gray": "#666666",
}


@dataclass(frozen=True)
class PanelInputs:
    """One isolated unshielded panel at each requested local angle."""

    delta_deg: FloatArray
    normals_in_stl: FloatArray
    tangent_hat_stl: FloatArray
    geometry: PanelGeometry
    flow_state: PanelFlowState


@dataclass(frozen=True)
class SentmanResponse:
    delta_deg: FloatArray
    normal_traction: FloatArray
    tangential_traction: FloatArray


@dataclass(frozen=True)
class WindwardResponse:
    delta_deg: FloatArray
    cp_by_equation: dict[str, FloatArray]
    cp_max: float
    wedge_limit_deg: float
    cone_limit_deg: float


@dataclass(frozen=True)
class LeewardResponse:
    delta_deg: FloatArray
    shield_cp: FloatArray
    prandtl_meyer_cp: FloatArray
    vacuum_cp: float


def _angle_grid(
    start_deg: float,
    stop_deg: float,
    *,
    extra_deg: tuple[float, ...] = (),
) -> FloatArray:
    count = round((stop_deg - start_deg) / ANGLE_STEP_DEG) + 1
    regular = np.linspace(start_deg, stop_deg, count, dtype=np.float64)
    extra = np.asarray(extra_deg, dtype=np.float64)
    angles = np.unique(np.concatenate((regular, extra)))
    if angles.ndim != 1 or angles.size == 0 or not np.isfinite(angles).all():
        raise RuntimeError("Local-angle grid must be a nonempty finite vector")
    if angles[0] < start_deg or angles[-1] > stop_deg:
        raise RuntimeError("Extra local angles must remain inside the plot range")
    return angles


def _panel_inputs(delta_deg: FloatArray) -> PanelInputs:
    angles = np.asarray(delta_deg, dtype=np.float64)
    if angles.ndim != 1 or angles.size == 0 or not np.isfinite(angles).all():
        raise RuntimeError("delta_deg must be a nonempty finite one-dimensional array")

    delta_rad = np.radians(angles)
    normals_in = np.column_stack(
        (np.sin(delta_rad), np.cos(delta_rad), np.zeros_like(delta_rad))
    )
    normals_out = -normals_in
    n_faces = angles.size
    geometry = PanelGeometry(
        centers_stl_m=np.zeros((n_faces, 3), dtype=np.float64),
        normals_out_stl=normals_out,
        areas_m2=np.ones(n_faces, dtype=np.float64),
        component_ids=np.zeros(n_faces, dtype=np.int64),
    )
    flow_state = PanelFlowState(
        velocity_hat_stl=FLOW_DIRECTION_STL,
        shielded=np.zeros(n_faces, dtype=np.bool_),
    )

    mu = normals_in @ FLOW_DIRECTION_STL
    tangent = np.zeros_like(normals_in)
    tangent_is_defined = np.abs(1.0 - np.abs(mu)) > 1.0e-12
    denominator = np.sqrt(np.maximum(1.0 - np.square(mu), 0.0))
    tangent[tangent_is_defined] = (
        FLOW_DIRECTION_STL[None, :]
        - mu[tangent_is_defined, None] * normals_in[tangent_is_defined]
    ) / denominator[tangent_is_defined, None]
    if not np.isfinite(tangent).all():
        raise RuntimeError("Panel tangent directions contain non-finite values")
    if not np.allclose(
        np.linalg.norm(tangent[tangent_is_defined], axis=1),
        1.0,
        rtol=0.0,
        atol=2.0e-12,
    ):
        raise RuntimeError("Defined panel tangent directions must be unit vectors")
    if np.any(flow_state.shielded):
        raise RuntimeError("Documentation curves must use only unshielded panels")
    return PanelInputs(angles, normals_in, tangent, geometry, flow_state)


def _index_at(delta_deg: FloatArray, target_deg: float) -> int:
    matches = np.flatnonzero(np.isclose(delta_deg, target_deg, rtol=0.0, atol=1e-10))
    if matches.size != 1:
        raise RuntimeError(f"Expected exactly one sample at delta={target_deg} deg")
    return int(matches[0])


def _require_finite(name: str, values: FloatArray) -> None:
    if values.ndim != 1 or not np.isfinite(values).all():
        raise RuntimeError(f"{name} must be a finite one-dimensional array")


def _sentman_response() -> SentmanResponse:
    panels = _panel_inputs(_angle_grid(-30.0, 90.0))
    case = ModelCasePayload(
        "sentman",
        {
            "S": SENTMAN_SPEED_RATIO,
            "Ti_K": SENTMAN_TI_K,
            "Mach": None,
            "Altitude_km": None,
            "Tw_K": SENTMAN_TW_K,
        },
    )
    loads = SentmanModel().evaluate(panels.geometry, panels.flow_state, case)
    traction = loads.traction_coeff_stl
    normal = np.asarray(
        loads.cell_scalars["normal_traction_coeff"],
        dtype=np.float64,
    )
    tangential = np.asarray(
        loads.cell_scalars["tangential_traction_coeff"],
        dtype=np.float64,
    )

    _require_finite("Sentman normal traction coefficient", normal)
    _require_finite("Sentman tangential traction coefficient", tangential)
    if normal.shape != panels.delta_deg.shape or tangential.shape != normal.shape:
        raise RuntimeError("Sentman response arrays do not match the angle grid")
    expected_normal = np.einsum("ij,ij->i", traction, panels.normals_in_stl)
    expected_tangential = np.einsum(
        "ij,ij->i",
        traction,
        panels.tangent_hat_stl,
    )
    if not np.allclose(normal, expected_normal, rtol=1.0e-12, atol=1.0e-13):
        maximum_error = float(np.max(np.abs(normal - expected_normal)))
        raise RuntimeError(
            "Sentman normal traction scalar is inconsistent with traction; "
            f"maximum absolute error={maximum_error:.3e}"
        )
    if not np.allclose(
        tangential,
        expected_tangential,
        rtol=1.0e-12,
        atol=1.0e-13,
    ):
        maximum_error = float(np.max(np.abs(tangential - expected_tangential)))
        raise RuntimeError(
            "Sentman tangential traction scalar is inconsistent with traction; "
            f"maximum absolute error={maximum_error:.3e}"
        )
    grazing = _index_at(panels.delta_deg, 0.0)
    facing = _index_at(panels.delta_deg, 90.0)
    if normal[grazing] <= 0.0 or tangential[grazing] <= 0.0:
        raise RuntimeError("Sentman grazing traction components must both be positive")
    if tangential[facing] != 0.0:
        raise RuntimeError(
            "Sentman tangential traction at 90 deg must use its zero limit"
        )
    return SentmanResponse(panels.delta_deg, normal, tangential)


def _hypersonic_cp(
    delta_deg: FloatArray,
    *,
    windward_eq: str,
    leeward_eq: str,
) -> FloatArray:
    panels = _panel_inputs(delta_deg)
    case = ModelCasePayload(
        "hypersonic",
        {
            "Mach": HYPERSONIC_MACH,
            "gamma": HYPERSONIC_GAMMA,
            "windward_eq": windward_eq,
            "leeward_eq": leeward_eq,
        },
    )
    loads = HypersonicModel().evaluate(panels.geometry, panels.flow_state, case)
    cp = np.asarray(loads.cell_scalars["cp"], dtype=np.float64)
    _require_finite(f"Hypersonic Cp ({windward_eq}, {leeward_eq})", cp)
    if cp.shape != panels.delta_deg.shape:
        raise RuntimeError("Hypersonic Cp array does not match the angle grid")
    expected_traction = cp[:, None] * panels.normals_in_stl
    if not np.allclose(
        loads.traction_coeff_stl,
        expected_traction,
        rtol=1.0e-12,
        atol=1.0e-13,
    ):
        raise RuntimeError("Hypersonic cp is inconsistent with pressure traction")
    return cp


def _validate_tangent_continuity(equation: str, limit_rad: float) -> None:
    epsilon_rad = 1.0e-10
    sample_deg = np.degrees(
        np.array(
            [limit_rad - epsilon_rad, limit_rad, limit_rad + epsilon_rad],
            dtype=np.float64,
        )
    )
    cp = _hypersonic_cp(
        sample_deg,
        windward_eq=equation,
        leeward_eq="shield",
    )
    if max(abs(cp[0] - cp[1]), abs(cp[2] - cp[1])) > 2.0e-5:
        raise RuntimeError(f"{equation} is not continuous at its attached limit")


def _windward_response() -> WindwardResponse:
    wedge_limit_rad, _wedge_cp = _tangent_wedge_detach_limit(
        HYPERSONIC_MACH,
        HYPERSONIC_GAMMA,
    )
    cone_limit_rad, _cone_cp = _tangent_cone_detach_limit(
        HYPERSONIC_MACH,
        HYPERSONIC_GAMMA,
    )
    wedge_limit_deg = math.degrees(wedge_limit_rad)
    cone_limit_deg = math.degrees(cone_limit_rad)
    delta_deg = _angle_grid(
        0.0,
        90.0,
        extra_deg=(wedge_limit_deg, cone_limit_deg),
    )
    equations = (
        "newtonian",
        "modified_newtonian",
        "tangent_wedge",
        "tangent_cone",
    )
    cp_by_equation = {
        equation: _hypersonic_cp(
            delta_deg,
            windward_eq=equation,
            leeward_eq="shield",
        )
        for equation in equations
    }
    cp_max = modified_newtonian_cp_max(HYPERSONIC_MACH, HYPERSONIC_GAMMA)
    grazing = _index_at(delta_deg, 0.0)
    facing = _index_at(delta_deg, 90.0)
    for equation, cp in cp_by_equation.items():
        _require_finite(f"Windward {equation} Cp", cp)
        if cp[grazing] != 0.0:
            raise RuntimeError(f"{equation} Cp must be zero at grazing incidence")
    if not math.isclose(
        float(cp_by_equation["newtonian"][facing]),
        2.0,
        rel_tol=0.0,
        abs_tol=1.0e-12,
    ):
        raise RuntimeError("Newtonian Cp at 90 deg must equal 2")
    for equation in ("modified_newtonian", "tangent_wedge", "tangent_cone"):
        if not math.isclose(
            float(cp_by_equation[equation][facing]),
            cp_max,
            rel_tol=1.0e-11,
            abs_tol=1.0e-12,
        ):
            raise RuntimeError(f"{equation} Cp at 90 deg must equal Cp_max")
    _validate_tangent_continuity("tangent_wedge", wedge_limit_rad)
    _validate_tangent_continuity("tangent_cone", cone_limit_rad)
    return WindwardResponse(
        delta_deg,
        cp_by_equation,
        cp_max,
        wedge_limit_deg,
        cone_limit_deg,
    )


def _leeward_response() -> LeewardResponse:
    delta_deg = _angle_grid(-50.0, 0.0)
    shield_cp = _hypersonic_cp(
        delta_deg,
        windward_eq="newtonian",
        leeward_eq="shield",
    )
    prandtl_meyer_cp = _hypersonic_cp(
        delta_deg,
        windward_eq="newtonian",
        leeward_eq="prandtl_meyer",
    )
    vacuum_cp = -2.0 / (HYPERSONIC_GAMMA * HYPERSONIC_MACH**2)
    if not np.array_equal(shield_cp, np.zeros_like(shield_cp)):
        raise RuntimeError("Leeward shield must assign exactly Cp=0")
    _require_finite("Prandtl-Meyer Cp", prandtl_meyer_cp)
    tolerance = 1.0e-12
    if np.any(prandtl_meyer_cp < vacuum_cp - tolerance) or np.any(
        prandtl_meyer_cp > tolerance
    ):
        raise RuntimeError("Prandtl-Meyer Cp must remain between vacuum and zero")
    if abs(float(prandtl_meyer_cp[0]) - vacuum_cp) > 1.0e-8:
        raise RuntimeError(
            "Prandtl-Meyer Cp at delta=-50 deg must reach the vacuum bound"
        )
    return LeewardResponse(
        delta_deg,
        shield_cp,
        prandtl_meyer_cp,
        vacuum_cp,
    )


def _new_figure() -> tuple[Figure, Axes]:
    figure, axes = plt.subplots(figsize=FIGURE_SIZE_IN, dpi=FIGURE_DPI)
    figure.subplots_adjust(left=0.115, right=0.975, bottom=0.13, top=0.875)
    axes.grid(True, color="#B0B0B0", linewidth=0.6, alpha=0.35)
    axes.set_axisbelow(True)
    return figure, axes


def _plot_values(values: FloatArray) -> FloatArray:
    """Suppress invisible platform-level floating noise in serialized paths."""
    return np.round(np.asarray(values, dtype=np.float64), PLOT_DECIMALS)


def _save_figure(figure: Figure, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(path, format="svg", dpi=FIGURE_DPI, metadata=SVG_METADATA)
    plt.close(figure)
    svg = path.read_text(encoding="utf-8")
    normalized = "\n".join(line.rstrip() for line in svg.splitlines()) + "\n"
    path.write_text(normalized, encoding="utf-8", newline="\n")


def _plot_sentman(response: SentmanResponse, path: Path) -> None:
    figure, axes = _new_figure()
    x = _plot_values(response.delta_deg)
    axes.axvspan(-30.0, 0.0, color=COLORS["gray"], alpha=0.1, zorder=0)
    axes.axvline(0.0, color=COLORS["gray"], linewidth=0.9, alpha=0.8)
    axes.plot(
        x,
        _plot_values(response.normal_traction),
        color=COLORS["blue"],
        linewidth=2.0,
        linestyle="-",
        label="Normal traction coeff.",
    )
    axes.plot(
        x,
        _plot_values(response.tangential_traction),
        color=COLORS["red"],
        linewidth=2.0,
        linestyle="--",
        label="Tangential traction coeff.",
    )
    axes.text(
        -15.0,
        0.76,
        "leeward orientation",
        transform=axes.get_xaxis_transform(),
        color=COLORS["gray"],
        fontsize=9,
        horizontalalignment="center",
        verticalalignment="top",
    )
    axes.annotate(
        "grazing, $\\delta=0$ deg",
        xy=(0.0, 0.0),
        xytext=(-12, 48),
        textcoords="offset points",
        color=COLORS["gray"],
        fontsize=9,
        horizontalalignment="right",
        arrowprops={
            "arrowstyle": "-",
            "color": COLORS["gray"],
            "linewidth": 0.8,
        },
        bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.88},
    )
    axes.set(
        title="Sentman local traction versus panel angle",
        xlabel=r"Local panel angle, $\delta$ [deg]",
        ylabel="Local traction coefficient",
        xlim=(-30.0, 90.0),
    )
    axes.legend(loc="upper left", framealpha=0.92)
    _save_figure(figure, path)


def _plot_windward(response: WindwardResponse, path: Path) -> None:
    figure, axes = _new_figure()
    x = _plot_values(response.delta_deg)
    axes.plot(
        x,
        _plot_values(response.cp_by_equation["newtonian"]),
        color=COLORS["blue"],
        linewidth=1.9,
        label="Newtonian",
    )
    axes.plot(
        x,
        _plot_values(response.cp_by_equation["modified_newtonian"]),
        color=COLORS["orange"],
        linewidth=1.9,
        label="Modified Newtonian",
    )
    tangent_specs = (
        (
            "tangent_wedge",
            "Tangent Wedge",
            response.wedge_limit_deg,
            COLORS["green"],
            (-84, -10),
        ),
        (
            "tangent_cone",
            "Tangent Cone",
            response.cone_limit_deg,
            COLORS["red"],
            (25, -112),
        ),
    )
    for equation, label, limit_deg, color, text_offset in tangent_specs:
        cp = _plot_values(response.cp_by_equation[equation])
        attached = response.delta_deg <= limit_deg
        continuation = response.delta_deg >= limit_deg
        axes.plot(
            x[attached],
            cp[attached],
            color=color,
            linewidth=2.1,
            linestyle="-",
            label=f"{label}: attached weak branch",
        )
        axes.plot(
            x[continuation],
            cp[continuation],
            color=color,
            linewidth=2.1,
            linestyle="--",
            label=f"{label}: continuation",
        )
        limit_index = _index_at(response.delta_deg, limit_deg)
        axes.axvline(
            round(limit_deg, PLOT_DECIMALS),
            color=color,
            linewidth=0.7,
            alpha=0.4,
        )
        axes.plot(
            [round(limit_deg, PLOT_DECIMALS)],
            [cp[limit_index]],
            marker="o",
            markersize=4.5,
            color=color,
            linestyle="none",
        )
        axes.annotate(
            f"{label} limit\n{limit_deg:.1f} deg",
            xy=(round(limit_deg, PLOT_DECIMALS), cp[limit_index]),
            xytext=text_offset,
            textcoords="offset points",
            color=color,
            fontsize=8,
            horizontalalignment=(
                "right" if equation == "tangent_wedge" else "left"
            ),
            arrowprops={"arrowstyle": "-", "color": color, "linewidth": 0.8},
            bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.88},
        )
    axes.axhline(
        response.cp_max,
        color=COLORS["purple"],
        linewidth=1.0,
        linestyle=":",
        label=r"Modified-Newtonian $C_{p,\max}$",
    )
    axes.set(
        title="Windward pressure models versus panel angle",
        xlabel=r"Local panel angle, $\delta$ [deg]",
        ylabel=r"Pressure coefficient, $C_p$",
        xlim=(0.0, 90.0),
        ylim=(0.0, 2.1),
    )
    axes.legend(loc="upper left", ncols=2, fontsize=7.8, framealpha=0.92)
    _save_figure(figure, path)


def _plot_leeward(response: LeewardResponse, path: Path) -> None:
    figure, axes = _new_figure()
    x = _plot_values(response.delta_deg)
    axes.plot(
        x,
        _plot_values(response.shield_cp),
        color=COLORS["blue"],
        linewidth=2.0,
        linestyle="--",
        label=r"leeward shield: $C_p=0$",
    )
    axes.plot(
        x,
        _plot_values(response.prandtl_meyer_cp),
        color=COLORS["red"],
        linewidth=2.0,
        linestyle="-",
        label="Prandtl-Meyer expansion",
    )
    axes.axhline(
        response.vacuum_cp,
        color=COLORS["gray"],
        linewidth=1.2,
        linestyle=":",
        label=r"Vacuum lower bound, $C_{p,\mathrm{vac}}$",
    )
    axes.set(
        title="Leeward pressure models versus panel angle",
        xlabel=r"Local panel angle, $\delta$ [deg]",
        ylabel=r"Pressure coefficient, $C_p$",
        xlim=(-50.0, 0.0),
        ylim=(response.vacuum_cp * 1.12, 0.004),
    )
    axes.legend(loc="upper left", framealpha=0.92)
    _save_figure(figure, path)


def _generate_all(output_dir: Path, *, announce: bool) -> tuple[Path, ...]:
    sentman = _sentman_response()
    windward = _windward_response()
    leeward = _leeward_response()
    paths = tuple(output_dir / name for name in OUTPUT_FILENAMES)
    _plot_sentman(sentman, paths[0])
    _plot_windward(windward, paths[1])
    _plot_leeward(leeward, paths[2])
    if announce:
        for path in paths:
            print(f"Generated {path}")
    return paths


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:12]


def _managed_svg_names(output_dir: Path) -> set[str]:
    if not output_dir.is_dir():
        return set()
    marker = GENERATOR_MARKER.encode()
    return {
        path.name
        for path in output_dir.glob("*.svg")
        if marker in path.read_bytes()
    }


def _check_generated(output_dir: Path) -> int:
    with tempfile.TemporaryDirectory(prefix="panelsolver-doc-plots-") as temporary:
        generated_dir = Path(temporary)
        generated = _generate_all(generated_dir, announce=False)
        expected_names = set(OUTPUT_FILENAMES)
        committed_names = _managed_svg_names(output_dir)
        failures: list[str] = []
        for temporary_path in generated:
            committed_path = output_dir / temporary_path.name
            if not committed_path.is_file():
                failures.append(f"missing: {committed_path}")
            elif temporary_path.read_bytes() != committed_path.read_bytes():
                failures.append(
                    f"outdated: {committed_path} "
                    f"(expected {_digest(temporary_path)}, found {_digest(committed_path)})"
                )
        for extra_name in sorted(committed_names - expected_names):
            failures.append(f"extra generated artifact: {output_dir / extra_name}")
        if failures:
            print("Documentation plot synchronization failed:")
            for failure in failures:
                print(f"  - {failure}")
            return 1
    print(f"Documentation plots are synchronized in {output_dir}")
    return 0


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in a temporary directory and compare SVG bytes",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="destination directory, or committed directory checked by --check",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    output_dir = args.output_dir.resolve()
    if args.check:
        return _check_generated(output_dir)
    _generate_all(output_dir, announce=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
