"""Shared command-line and graphical application layer."""

from .artifact_io import write_vtp_projection
from .attitude import ATTITUDE_INPUT_VALUES, ResolvedAttitude, resolve_attitude
from .case_adapter import (
    AdaptedCase,
    ProductCasePolicy,
    adapt_case_row,
)
from .case_io import (
    CaseReaderPolicy,
    InputValidationError,
    ValidationIssue,
    read_case_table,
)
from .csv_writer import (
    DURABLE_CSV_WRITE_POLICY,
    AtomicCsvWritePolicy,
    TempNameStyle,
    validate_csv_output_path,
    validate_summary_output_path,
    write_csv_atomic,
)
from .examples import ExampleDefinition, ExampleLibrary, ExampleResourceError
from .execution import default_model_registry, request_from_registry
from .output_status import (
    OutputFailuresError,
    OutputIssue,
    OutputKind,
    OutputPhase,
)
from .path_resolution import (
    DEFAULT_IMAGE_DIRECTORY,
    DEFAULT_OUTPUT_DIRECTORY,
    absolute_input_path,
    auto_rename_path,
    default_image_filename,
    default_summary_output_path,
    resolve_batch_image_dir,
    resolve_case_image_dir,
    resolve_case_image_path,
    resolve_case_output_dir,
    resolve_case_vtp_path,
    resolve_input_relative_path,
    resolve_manual_vtp_image_path,
)
from .runtime import (
    DEFAULT_CHECKPOINT_CASES,
    PreparedProductCase,
    ProductBatchRunResult,
    ProductCaseRunResult,
    ProductProjectionAdditions,
    ProductRuntimePolicy,
    combine_csv_projections,
    prepare_product_cases,
    run_and_write_product_cases,
    run_product_cases,
)
from .solver_spec import (
    COMMON_SCALAR_LABELS,
    CaseColumnKind,
    CaseColumnPresentation,
    CaseColumnWidthRole,
    GuiRunRequest,
    GuiRunResult,
    SolverGuiAdapters,
    SolverSpec,
    gui_run_result_from_batch,
)
from .viewer_data import (
    ArtifactCaseMatch,
    ArtifactLoadMode,
    ArtifactViewState,
    ArtifactViewStatus,
    ScalarField,
    artifact_display_allowed,
    automatic_artifact_view_state,
    discover_scalar_fields,
    field_data_scalar,
    manual_artifact_view_state,
    match_artifact_case,
    resolve_matching_case_row,
    scalar_color_limits,
)

__all__ = (
    "ATTITUDE_INPUT_VALUES",
    "COMMON_SCALAR_LABELS",
    "DEFAULT_CHECKPOINT_CASES",
    "DEFAULT_IMAGE_DIRECTORY",
    "DEFAULT_OUTPUT_DIRECTORY",
    "DURABLE_CSV_WRITE_POLICY",
    "AdaptedCase",
    "ArtifactCaseMatch",
    "ArtifactLoadMode",
    "ArtifactViewState",
    "ArtifactViewStatus",
    "AtomicCsvWritePolicy",
    "CaseColumnKind",
    "CaseColumnPresentation",
    "CaseColumnWidthRole",
    "CaseReaderPolicy",
    "ExampleDefinition",
    "ExampleLibrary",
    "ExampleResourceError",
    "GuiRunRequest",
    "GuiRunResult",
    "InputValidationError",
    "OutputFailuresError",
    "OutputIssue",
    "OutputKind",
    "OutputPhase",
    "PreparedProductCase",
    "ProductBatchRunResult",
    "ProductCasePolicy",
    "ProductCaseRunResult",
    "ProductProjectionAdditions",
    "ProductRuntimePolicy",
    "ResolvedAttitude",
    "ScalarField",
    "SolverGuiAdapters",
    "SolverSpec",
    "TempNameStyle",
    "ValidationIssue",
    "absolute_input_path",
    "adapt_case_row",
    "artifact_display_allowed",
    "auto_rename_path",
    "automatic_artifact_view_state",
    "combine_csv_projections",
    "default_image_filename",
    "default_model_registry",
    "default_summary_output_path",
    "discover_scalar_fields",
    "field_data_scalar",
    "gui_run_result_from_batch",
    "manual_artifact_view_state",
    "match_artifact_case",
    "prepare_product_cases",
    "read_case_table",
    "request_from_registry",
    "resolve_attitude",
    "resolve_batch_image_dir",
    "resolve_case_image_dir",
    "resolve_case_image_path",
    "resolve_case_output_dir",
    "resolve_case_vtp_path",
    "resolve_input_relative_path",
    "resolve_manual_vtp_image_path",
    "resolve_matching_case_row",
    "run_and_write_product_cases",
    "run_product_cases",
    "scalar_color_limits",
    "validate_csv_output_path",
    "validate_summary_output_path",
    "write_csv_atomic",
    "write_vtp_projection",
)
